#!/usr/bin/env escript

-export([main/1]).

main([]) ->
    io:format("Usage: \n" ++
		  " export VIEWER=firefox \n" ++
		  " fsm_dynamic File.erl [PZ] - compiles File_tests.erl into minimal FSM and" ++
		  " visualize it in $VIEWER\n" );
main([File_Name]) ->
    compile(File_Name, []);
main([File_Name, EUnit_Dir]) ->
    code:add_pathz(EUnit_Dir),
    compile(File_Name, [{i, EUnit_Dir}]).

compile(File_Name, Options) ->
    %% io:format(">> ~p~n", [filename:absname("")]),
    ExtraPath = ["ebin", ".eunit", "deps/*/ebin", "./include", "./test"],
    lists:foreach(fun(P) -> code:add_pathz(P) end, ExtraPath), 
    %% io:format(">> ~p~n", [code:get_path()]),
    ExtraOptions = [{i, P} || P <- ExtraPath]
	++ [verbose, {i, filename:absname("") ++ "/deps"}, {d, 'VZTEST', true}],
    %% io:format(">> ~p ~p ~n", [File_Name, ExtraOptions ++ Options]),
    {{Pos,Neg},_CleanupTree} = eunit_to_fsm:dynamic(File_Name, ExtraOptions ++ Options),
    %% io:format(user, "Pos: ~p~n", [Pos]),
    %% io:format(user, "Neg: ~p~n", [Neg]),
    Automata = bluefringe:qsm({Pos,Neg}),
    bluefringe_dot:visualize(Automata).
